[context]
name = "const-macros"
version = "0.2.0"
url = "https://github.com/nekitdev/const-macros"

[formats]
title = "[{{version}}]({{url}}/tree/v{{version}}) ({{date}})"
fragment = "{{content}} ([#{{id}}]({{url}}/pull/{{id}}))"
